// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from 'react-router'

// Imports for page components
import * as SyncComponent0 from './pages/login.sync'
import * as SyncComponent1 from './pages/(main)/batches.sync'
import * as SyncComponent2 from './pages/(main)/datasets.sync'
import * as SyncComponent3 from './pages/(main)/label-sets.sync'
import * as SyncComponent5 from './pages/(main)/index.sync'

// Generated route configuration
export const routes: RouteObject[] = [
  {
    path: 'login',
    Component: SyncComponent0.Component,
    loader: SyncComponent0.loader,
    handle: SyncComponent0.handle,
  },
  {
    path: '',
    children: [
      {
        path: 'batches',
        Component: SyncComponent1.Component,
        loader: SyncComponent1.loader,
        handle: SyncComponent1.handle,
      },
      {
        path: 'datasets',
        Component: SyncComponent2.Component,
        loader: SyncComponent2.loader,
        handle: SyncComponent2.handle,
      },
      {
        path: 'label-sets',
        Component: SyncComponent3.Component,
        loader: SyncComponent3.loader,
        handle: SyncComponent3.handle,
      },
      {
        path: '',
        Component: SyncComponent5.Component,
        loader: SyncComponent5.loader,
        handle: SyncComponent5.handle,
      },
    ],
  },
]

export default routes
